---
argument_specs:
  main:
    short_description: Deploy Helm charts from OCI registries.

    options:

      releases:
        type: list
        required: true
        elements: dict
        options:
          name:
            type: str
            required: true

          namespace:
            type: str
            required: true

          chart_ref:
            type: str
            required: true
            description: |
              OCI chart reference like:
              oci://registry.example.com/mychart

          chart_version:
            type: str

          values:
            type: dict

          values_files:
            type: list
            elements: str

          wait:
            type: bool
            default: true

          atomic:
            type: bool
            default: true

          wait_timeout:
            type: str
            
      release_common_opts:
        type: dict
        default: {}
        options:
          wait:
            type: bool
            default: true
          atomic:
            type: bool
            default: true
          wait_timeout:
            type: str
            default: "5m"
          create_namespace:
            type: bool
            default: true