# This inventory describe a HA typology with stacked etcd (== same nodes as control plane)
# and 3 worker nodes
# See https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html
# for tips on building your # inventory

# Configure 'ip' variable to bind kubernetes services on a different ip than the default iface
# We should set etcd_member_name for etcd cluster. The node that are not etcd members do not need to set the value,
# or can set the empty string value.

# label for specific node kubemaster02 ansible_host=192.168.0.137 ip=192.168.0.137 ansible_user=root node_labels='{"role":"master","provider":"kubespray"}'

[kube_control_plane]
# Master nodes
kubemaster01 ansible_host=192.168.0.136 ip=192.168.0.136 ansible_user=root
kubemaster02 ansible_host=192.168.0.137 ip=192.168.0.137 ansible_user=root
kubemaster03 ansible_host=192.168.0.138 ip=192.168.0.138 ansible_user=root

[etcd]
# Dedicated etcd nodes
etcd01 ansible_host=192.168.0.141 etcd_member_name=etcd01 ansible_user=root 
etcd02 ansible_host=192.168.0.142 etcd_member_name=etcd02 ansible_user=root
etcd03 ansible_host=192.168.0.143 etcd_member_name=etcd03 ansible_user=root

# If you want etcd to be part of the control plane, you would use [etcd:children]
# and remove the dedicated [etcd] group.
# For example, if etcd was on the master nodes:
# [etcd:children]
# kube_control_plane

[kube_node]
# Worker nodes
kubeworker01 ansible_host=192.168.0.139 ip=192.168.0.139 ansible_user=root
kubeworker02 ansible_host=192.168.0.140 ip=192.168.0.140 ansible_user=root

# Load Balancers (HAProxy)
[loadbalancers]
haproxy01 ansible_host=192.168.0.144 ansible_user=root
haproxy02 ansible_host=192.168.0.145 ansible_user=root

# Group for all nodes that will run Kubernetes components
[k8s_cluster:children]
kube_control_plane
kube_node

[db_nodes_taints]
kubeworker01

[ceph_nodes_taints]
kubeworker02

[worker_nodes_labels:children]
kube_node

[master_nodes_labels:children]
kube_control_plane

[test_label:children]
kube_node

[test_taint]
kubeworker02