environments:
  - name: sandbox
    services:
      - name: kubernetes
        nodes:
          - ip: <SANDBOX_K8S_NODE_1_IP>
            hostname: <SANDBOX_K8S_NODE_1_HOST>
          - ip: <SANDBOX_K8S_NODE_2_IP>
            hostname: <SANDBOX_K8S_NODE_2_HOST>
      - name: harbor
        nodes:
          - ip: <SANDBOX_HARBOR_IP>
            hostname: <SANDBOX_HARBOR_HOST>
      - name: ceph
        nodes:
          - ip: <SANDBOX_CEPH_NODE_1_IP>
            hostname: <SANDBOX_CEPH_NODE_1_HOST>
