apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
    version: {{ .Chart.AppVersion }}
type: Opaque
stringData:
  JIRA_TOKEN: {{ .Values.jiraToken | quote }}
  WEBHOOK_SECRET: {{ .Values.webhookSecret | quote }}