include:
  - local: ci/stages.yml
  - local: ci/templates.yml
  - local: ci/jobs/check.yml
  - local: ci/jobs/install.yml
  - local: ci/jobs/cilium.yml
  - local: ci/jobs/argocd.yml
  - local: ci/jobs/label.yml
  - local: ci/jobs/taint.yml
  - local: ci/jobs/upgrade.yml
  - local: ci/jobs/reset.yml